config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts
  resources :comments, only: [:create]

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  post "/graphql", to: "graphql#execute"

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  namespace :admin do
    root to: "users#index"

    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role

  has_many :posts
  has_many :comments

  validates :email, :name, :role, presence: true

  # list of searchable attributes
  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  def admin?
    role.title == 'admin'
  end

  def editor?
    role.title == 'editor'
  end

  def writer?
    role.title == 'writer'
  end

  def read_only?
    role.title == 'readonly'
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    def index
      authorize :user_dashboard, :index?

      @users = User.all.order(id: :desc)
    end

    def edit
      authorize :user_dashboard, :edit?

      @user = User.find(params[:id])
    end

    def update
      authorize :user_dashboard, :update?

      @user = User.find(params[:id])

      @user.update(user_params)
      redirect_to admin_users_path
    end

    private

    def user_params
      params.require(:user).permit(:role_id)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/users/edit.html.erb
<%= form_with(model: [:admin, @user]) do |form| %>
  <div class="mb-4">
    <span class="block text-gray-700 text-sm font-bold mb-2">
      ID: <%= @user.id %>
    </span>
    <span class="block text-gray-700 text-sm font-bold mb-2">
      Email: <%= @user.email %>
    </span>
    <span class="block text-gray-700 text-sm font-bold mb-2">
      Name: <%= @user.name %>
    </span>

    <%= form.select :role_id, options_from_collection_for_select(Role.all, :id, :title, @user.role_id), class: "shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  <div class="flex items-center justify-between">
    <%= form.submit "Update", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<table class="min-w-max w-full divide-y divide-gray-200">
  <thead>
    <tr>
      <th class="py-3 px-6 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase">id</th>
      <th class="py-3 px-6 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase">name</th>
      <th class="py-3 px-6 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase">email</th>
      <th class="py-3 px-6 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase">role</th>
      <th class="py-3 px-6 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase">created_at</th>
      <th class="py-3 px-6 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase">updated_at</th>
      <th class="py-3 px-6 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase">actions</th>
    </tr>
  </thead>
  <tbody class="bg-white divide-y divide-gray-200">
    <% @users.each do |user| %>
      <tr>
        <td class="py-4 px-6 whitespace-nowrap w-16"><%= user.id %></td>
        <td class="py-4 px-6 whitespace-nowrap"><%= user.name %></td>
        <td class="py-4 px-6 whitespace-nowrap"><%= user.email %></td>
        <td class="py-4 px-6 whitespace-nowrap"><%= user.role.title %></td>
        <td class="py-4 px-6 whitespace-nowrap"><%= user.created_at.to_formatted_s(:long) %></td>
        <td class="py-4 px-6 whitespace-nowrap"><%= user.updated_at.to_formatted_s(:long) %></td>
        <td class="py-4 px-6 whitespace-nowrap">
          <%= link_to 'edit', edit_admin_user_path(user), class: "text-blue-500 hover:text-blue-700" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>